"""
CLIP-Based AI Image Detector
==============================
Uses OpenAI's CLIP (ViT-L/14) as a zero-shot or fine-tuned detector.

Why CLIP works where ViT fails:
- CLIP understands image SEMANTICS, not just pixel patterns
- AI images have subtle compositional tells (too-perfect symmetry,
  inconsistent lighting, anatomically plausible but statistically unusual poses)
- These semantic features SURVIVE compression because they're about
  content, not pixel-level artifacts
- CLIP embeddings are robust to JPEG compression, resizing, and re-sharing

Two modes:
1. Zero-shot: Uses CLIP's text-image alignment to compare the image
   against prompts like "a real photograph" vs "an AI generated image"
2. Linear probe: Trains a small classifier on CLIP embeddings (more accurate)
"""

import os
import numpy as np
import cv2
from typing import Tuple, Dict, Any

try:
    import torch
    import torch.nn as nn
    HAS_TORCH = True
except ImportError:
    HAS_TORCH = False

try:
    from transformers import CLIPProcessor, CLIPModel
    HAS_CLIP = True
except ImportError:
    HAS_CLIP = False


class CLIPDetector:
    """
    CLIP-based AI image detector with zero-shot and linear probe modes.
    """

    # Zero-shot prompts calibrated for AI detection
    REAL_PROMPTS = [
        "a real photograph taken by a camera",
        "an authentic unedited photograph",
        "a genuine photo of a real scene",
        "a natural photograph with real lighting",
    ]
    AI_PROMPTS = [
        "an AI generated image",
        "a synthetic image created by artificial intelligence",
        "a computer generated fake image",
        "an image generated by Midjourney or DALL-E or Stable Diffusion",
    ]

    def __init__(
        self,
        model_name: str = "openai/clip-vit-large-patch14",
        probe_weights_path: str = None,
        device: str = None,
    ):
        if not HAS_TORCH or not HAS_CLIP:
            raise RuntimeError("torch and transformers required for CLIPDetector")

        self.device = torch.device(device) if device else torch.device(
            "cuda" if torch.cuda.is_available() else "cpu"
        )

        print(f"[CLIP] Loading {model_name}...")
        self.model = CLIPModel.from_pretrained(model_name)
        self.processor = CLIPProcessor.from_pretrained(model_name)
        self.model.to(self.device).eval()
        print(f"[CLIP] Loaded on {self.device}")

        # Linear probe head (optional, for fine-tuned mode)
        self.probe = None
        if probe_weights_path and os.path.exists(probe_weights_path):
            self._load_probe(probe_weights_path)

    def _load_probe(self, path: str):
        """Load a trained linear probe classifier."""
        checkpoint = torch.load(path, map_location=self.device, weights_only=False)
        embed_dim = checkpoint.get("embed_dim", 768)
        self.probe = nn.Sequential(
            nn.Linear(embed_dim, 256),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(256, 2),
        ).to(self.device)
        self.probe.load_state_dict(checkpoint["probe_state_dict"])
        self.probe.eval()
        print(f"[CLIP] Linear probe loaded from {path}")

    @torch.no_grad()
    def predict_zero_shot(self, image: np.ndarray) -> Tuple[float, Dict]:
        """
        Zero-shot prediction: compare image against real vs AI text prompts.
        No training needed — works immediately on any image.

        Returns (ai_probability, details)
        """
        if image is None:
            return 0.5, {"status": "error", "reason": "invalid image"}

        try:
            # Convert BGR to RGB
            rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

            all_prompts = self.REAL_PROMPTS + self.AI_PROMPTS
            inputs = self.processor(
                text=all_prompts,
                images=rgb,
                return_tensors="pt",
                padding=True,
            )
            inputs = {k: v.to(self.device) for k, v in inputs.items()}

            outputs = self.model(**inputs)
            logits = outputs.logits_per_image[0]  # (num_prompts,)

            # Split scores for real vs AI prompts
            n_real = len(self.REAL_PROMPTS)
            real_scores = logits[:n_real]
            ai_scores = logits[n_real:]

            # Average similarity to real vs AI prompts
            avg_real = real_scores.mean().item()
            avg_ai = ai_scores.mean().item()

            # Convert to probability via softmax over the two averages
            combined = torch.softmax(torch.tensor([avg_real, avg_ai]), dim=0)
            ai_prob = combined[1].item()

            return ai_prob, {
                "status": "success",
                "method": "zero_shot",
                "ai_probability": round(ai_prob, 4),
                "real_similarity": round(avg_real, 4),
                "ai_similarity": round(avg_ai, 4),
            }

        except Exception as e:
            return 0.5, {"status": "error", "reason": str(e)}

    @torch.no_grad()
    def extract_embedding(self, image: np.ndarray) -> torch.Tensor:
        """Extract CLIP image embedding (for linear probe or fusion)."""
        rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        inputs = self.processor(images=rgb, return_tensors="pt")
        inputs = {k: v.to(self.device) for k, v in inputs.items()}
        features = self.model.get_image_features(**inputs)
        # L2 normalize
        features = features / features.norm(dim=-1, keepdim=True)
        return features

    @torch.no_grad()
    def predict_probe(self, image: np.ndarray) -> Tuple[float, Dict]:
        """
        Linear probe prediction (requires trained probe weights).
        More accurate than zero-shot but needs training data.
        """
        if self.probe is None:
            return self.predict_zero_shot(image)

        try:
            embedding = self.extract_embedding(image)
            logits = self.probe(embedding)
            probs = torch.softmax(logits, dim=-1)[0]
            ai_prob = probs[1].item()

            return ai_prob, {
                "status": "success",
                "method": "linear_probe",
                "ai_probability": round(ai_prob, 4),
                "real_probability": round(probs[0].item(), 4),
            }

        except Exception as e:
            return self.predict_zero_shot(image)

    def predict(self, image: np.ndarray) -> Tuple[float, Dict]:
        """Main prediction: uses probe if available, else zero-shot."""
        if self.probe is not None:
            return self.predict_probe(image)
        return self.predict_zero_shot(image)
