"""
Audio-Visual Synchronization Analyzer
=======================================
Detects AI-generated video by analyzing the synchronization between
lip movements and audio speech patterns.

THEORETICAL FOUNDATION:
━━━━━━━━━━━━━━━━━━━━━━━
Real human speech involves tightly synchronized audio and visual signals:
  - Lip opening correlates with vowel sounds (high audio energy)
  - Lip closure correlates with plosive consonants (brief silence then burst)
  - Typical audio-visual delay: 0-80ms (within perceptual threshold)
  - Correlation coefficient between lip movement and audio energy: 0.5-0.8

AI-generated video has poor audio-visual sync because:
  - Video and audio are often generated by separate models
  - Even joint models can't perfectly model articulatory phonetics
  - Temporal alignment is approximate, not physically grounded
  - Lip shapes may not match the phonemes being spoken
  - Correlation is typically 0.1-0.3 (much lower than real speech)

ANALYSIS LAYERS:
━━━━━━━━━━━━━━━━
1. Audio-Lip Cross-Correlation
   - Correlate audio envelope with lip opening signal
   - Real: high peak correlation (0.4-0.8) at near-zero lag
   - AI: low correlation, variable lag

2. Phoneme-Viseme Consistency
   - Map audio energy bursts to lip movement events
   - Real: 1:1 correspondence with consistent timing
   - AI: missing or extra lip movements, inconsistent timing

3. Speech Rhythm Alignment
   - Analyze speech rhythm (syllable rate) in audio
   - Compare with lip movement periodicity
   - Real: matching frequencies, AI: frequency mismatch

4. Silence-Stillness Correspondence
   - During audio silence, lips should be relatively still
   - AI often generates lip movement during silence or vice versa
"""

import cv2
import numpy as np
import subprocess
import tempfile
import os
from typing import Dict, Any, Tuple, List, Optional


class AudioVisualSyncAnalyzer:
    """
    Analyzes audio-visual synchronization to detect AI-generated video.
    Focuses on lip movement vs audio energy correlation.
    """

    def __init__(self, verbose: bool = False):
        self.verbose = verbose
        self.face_cascade = cv2.CascadeClassifier(
            cv2.data.haarcascades + "haarcascade_frontalface_default.xml"
        )

    def analyze(self, video_path: str) -> Dict[str, Any]:
        """
        Run full audio-visual sync analysis.

        Returns dict with ai_probability and detailed metrics.
        """
        # Extract audio
        audio, audio_sr = self._extract_audio(video_path)
        if audio is None:
            return {
                "ai_probability": 0.5,
                "metrics": {"error": "Could not extract audio (no audio track or ffmpeg unavailable)"},
            }

        # Check if audio has speech (skip if just music/silence)
        has_speech = self._detect_speech_presence(audio, audio_sr)
        if not has_speech:
            return {
                "ai_probability": 0.5,
                "metrics": {"note": "No speech detected in audio, AV sync analysis skipped"},
            }

        # Extract lip movement signal from video
        lip_signal, video_fps = self._extract_lip_movement(video_path)
        if lip_signal is None or len(lip_signal) < 30:
            return {
                "ai_probability": 0.5,
                "metrics": {"error": "Could not track lip movement (no face detected)",
                            "lip_frames": len(lip_signal) if lip_signal is not None else 0},
            }

        # Compute audio envelope at video frame rate
        audio_envelope = self._compute_audio_envelope(audio, audio_sr, video_fps, len(lip_signal))

        if len(audio_envelope) != len(lip_signal):
            min_len = min(len(audio_envelope), len(lip_signal))
            audio_envelope = audio_envelope[:min_len]
            lip_signal = lip_signal[:min_len]

        # Layer 1: Audio-Lip Cross-Correlation
        corr_score, corr_metrics = self._analyze_cross_correlation(
            audio_envelope, lip_signal, video_fps
        )

        # Layer 2: Energy Event Correspondence
        event_score, event_metrics = self._analyze_event_correspondence(
            audio_envelope, lip_signal, video_fps
        )

        # Layer 3: Speech Rhythm Alignment
        rhythm_score, rhythm_metrics = self._analyze_speech_rhythm(
            audio_envelope, lip_signal, video_fps
        )

        # Layer 4: Silence-Stillness Correspondence
        silence_score, silence_metrics = self._analyze_silence_stillness(
            audio_envelope, lip_signal
        )

        # Weighted ensemble
        weights = {
            "cross_correlation": (corr_score, 1.5),
            "event_correspondence": (event_score, 1.2),
            "speech_rhythm": (rhythm_score, 1.0),
            "silence_stillness": (silence_score, 1.3),
        }

        total_w = sum(w for _, w in weights.values())
        ai_probability = sum(s * w for s, w in weights.values()) / total_w
        ai_probability = float(np.clip(ai_probability, 0, 1))

        if self.verbose:
            for name, (score, _) in weights.items():
                print(f"  [AV-Sync] {name}: {score:.4f}")

        return {
            "ai_probability": round(ai_probability, 4),
            "layer_scores": {
                name: round(score, 4) for name, (score, _) in weights.items()
            },
            "metrics": {
                "correlation": corr_metrics,
                "events": event_metrics,
                "rhythm": rhythm_metrics,
                "silence": silence_metrics,
                "audio_duration": round(len(audio) / audio_sr, 1),
                "lip_frames": len(lip_signal),
                "video_fps": round(video_fps, 1),
            },
        }

    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    # Audio Extraction
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    def _extract_audio(
        self, video_path: str
    ) -> Tuple[Optional[np.ndarray], int]:
        """
        Extract audio from video file using ffmpeg.
        Returns (audio_samples, sample_rate) or (None, 0).
        """
        target_sr = 16000

        try:
            # Create temp wav file
            tmp_wav = tempfile.mktemp(suffix=".wav")

            # Use ffmpeg to extract audio
            cmd = [
                "ffmpeg", "-i", video_path,
                "-vn",  # no video
                "-acodec", "pcm_s16le",
                "-ar", str(target_sr),
                "-ac", "1",  # mono
                "-y",  # overwrite
                tmp_wav,
            ]

            result = subprocess.run(
                cmd, capture_output=True, timeout=30,
                creationflags=subprocess.CREATE_NO_WINDOW if os.name == 'nt' else 0,
            )

            if result.returncode != 0 or not os.path.exists(tmp_wav):
                return None, 0

            # Load wav file
            try:
                from scipy.io import wavfile
                sr, audio = wavfile.read(tmp_wav)
                audio = audio.astype(np.float32) / 32768.0  # normalize to [-1, 1]
            except ImportError:
                # Manual WAV reading fallback
                with open(tmp_wav, 'rb') as f:
                    f.read(44)  # skip WAV header
                    raw = np.frombuffer(f.read(), dtype=np.int16)
                    audio = raw.astype(np.float32) / 32768.0
                    sr = target_sr

            os.unlink(tmp_wav)

            if len(audio) < sr:  # Less than 1 second
                return None, 0

            return audio, sr

        except (FileNotFoundError, subprocess.TimeoutExpired, Exception):
            # ffmpeg not available
            return None, 0

    def _detect_speech_presence(
        self, audio: np.ndarray, sr: int
    ) -> bool:
        """
        Simple speech presence detection using energy and zero-crossing rate.
        """
        # Frame-level energy
        frame_len = int(0.025 * sr)  # 25ms frames
        hop = int(0.010 * sr)  # 10ms hop

        energies = []
        zcrs = []

        for i in range(0, len(audio) - frame_len, hop):
            frame = audio[i:i + frame_len]
            energy = float(np.sum(frame ** 2))
            zcr = float(np.sum(np.abs(np.diff(np.sign(frame)))) / (2 * len(frame)))
            energies.append(energy)
            zcrs.append(zcr)

        if not energies:
            return False

        # Speech: moderate energy (not silence, not just noise) + ZCR pattern
        energy_threshold = np.percentile(energies, 30)
        speech_frames = sum(1 for e, z in zip(energies, zcrs)
                          if e > energy_threshold and 0.02 < z < 0.15)

        speech_ratio = speech_frames / len(energies)
        return speech_ratio > 0.15  # At least 15% of frames appear to be speech

    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    # Lip Movement Extraction
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    def _extract_lip_movement(
        self, video_path: str
    ) -> Tuple[Optional[np.ndarray], float]:
        """
        Extract lip movement signal from video frames.

        Without facial landmarks (dlib), we approximate mouth openness using:
        1. Detect face bounding box
        2. Crop lower 30% of face (mouth region)
        3. Compute vertical gradient energy in mouth region
           (open mouth = strong horizontal edges from lip boundaries)
        4. Track this signal over time

        Returns (lip_movement_signal, fps)
        """
        cap = cv2.VideoCapture(video_path)
        if not cap.isOpened():
            return None, 0

        fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
        total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

        lip_signals = []
        stable_bbox = None
        ema_alpha = 0.2

        for frame_idx in range(min(total, int(fps * 20))):  # max 20 seconds
            ret, frame = cap.read()
            if not ret:
                break

            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

            # Detect face
            faces = self.face_cascade.detectMultiScale(
                gray, scaleFactor=1.1, minNeighbors=5, minSize=(80, 80)
            )

            if len(faces) > 0:
                bbox = max(faces, key=lambda f: f[2] * f[3])
                x, y, w, h = bbox

                if stable_bbox is not None:
                    stable_bbox = (
                        int(stable_bbox[0] * (1 - ema_alpha) + x * ema_alpha),
                        int(stable_bbox[1] * (1 - ema_alpha) + y * ema_alpha),
                        int(stable_bbox[2] * (1 - ema_alpha) + w * ema_alpha),
                        int(stable_bbox[3] * (1 - ema_alpha) + h * ema_alpha),
                    )
                else:
                    stable_bbox = (x, y, w, h)

            if stable_bbox is None:
                continue

            x, y, w, h = stable_bbox
            fh, fw = frame.shape[:2]

            # Mouth region: lower 30% of face, inner 60% width
            mouth_y1 = min(fh - 1, y + int(h * 0.65))
            mouth_y2 = min(fh, y + int(h * 0.95))
            mouth_x1 = max(0, x + int(w * 0.20))
            mouth_x2 = min(fw, x + int(w * 0.80))

            mouth_roi = gray[mouth_y1:mouth_y2, mouth_x1:mouth_x2]

            if mouth_roi.size == 0 or mouth_roi.shape[0] < 5:
                lip_signals.append(0.0)
                continue

            # Compute vertical gradient energy (horizontal edges from lip boundaries)
            gy = cv2.Sobel(mouth_roi, cv2.CV_64F, 0, 1, ksize=3)
            lip_openness = float(np.mean(np.abs(gy)))

            # Also compute the variance of the mouth region
            # (open mouth = higher variance from teeth/darkness contrast)
            mouth_var = float(np.var(mouth_roi.astype(np.float32)))

            # Combined lip movement signal
            lip_signal = lip_openness * 0.6 + np.sqrt(mouth_var) * 0.4
            lip_signals.append(lip_signal)

        cap.release()

        if len(lip_signals) < 30:
            return None, fps

        return np.array(lip_signals), fps

    def _compute_audio_envelope(
        self, audio: np.ndarray, audio_sr: int,
        video_fps: float, n_frames: int,
    ) -> np.ndarray:
        """
        Compute audio energy envelope at video frame rate.
        """
        # Samples per video frame
        spf = audio_sr / video_fps
        envelope = []

        for i in range(n_frames):
            start = int(i * spf)
            end = int((i + 1) * spf)
            if end > len(audio):
                break
            frame_audio = audio[start:end]
            energy = float(np.sqrt(np.mean(frame_audio ** 2)))  # RMS
            envelope.append(energy)

        return np.array(envelope)

    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    # Layer 1: Cross-Correlation
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    def _analyze_cross_correlation(
        self, audio_env: np.ndarray, lip_signal: np.ndarray,
        fps: float,
    ) -> Tuple[float, Dict]:
        """
        Compute cross-correlation between audio envelope and lip movement.

        Real speech: peak correlation 0.4-0.8 at lag near 0 (±3 frames)
        AI video: low correlation (<0.3) or peak at wrong lag
        """
        # Normalize both signals
        audio_norm = (audio_env - audio_env.mean()) / (audio_env.std() + 1e-8)
        lip_norm = (lip_signal - lip_signal.mean()) / (lip_signal.std() + 1e-8)

        # Cross-correlation with lag range ±15 frames (~±0.5 seconds)
        max_lag = min(15, len(audio_norm) // 4)
        n = len(audio_norm)

        correlations = []
        lags = list(range(-max_lag, max_lag + 1))

        for lag in lags:
            if lag >= 0:
                a = audio_norm[lag:]
                l = lip_norm[:n - lag]
            else:
                a = audio_norm[:n + lag]
                l = lip_norm[-lag:]

            min_len = min(len(a), len(l))
            if min_len < 10:
                correlations.append(0.0)
                continue

            corr = float(np.corrcoef(a[:min_len], l[:min_len])[0, 1])
            correlations.append(corr if not np.isnan(corr) else 0.0)

        correlations = np.array(correlations)
        peak_idx = np.argmax(correlations)
        peak_corr = float(correlations[peak_idx])
        peak_lag = lags[peak_idx]
        peak_lag_ms = (peak_lag / fps) * 1000  # Convert to milliseconds

        # Also compute zero-lag correlation
        zero_lag_idx = max_lag  # index of lag=0
        zero_lag_corr = float(correlations[zero_lag_idx])

        # Score
        # Low correlation = likely AI
        # peak_corr: real ~0.4-0.8, AI ~0.0-0.3
        corr_score = np.clip((0.35 - peak_corr) / 0.30, 0, 1)

        # Lag penalty: if peak is far from zero, something is wrong
        lag_penalty = np.clip(abs(peak_lag_ms) / 300.0, 0, 0.3)

        combined = corr_score + lag_penalty
        combined = float(np.clip(combined, 0, 1))

        metrics = {
            "peak_correlation": round(peak_corr, 4),
            "peak_lag_frames": peak_lag,
            "peak_lag_ms": round(peak_lag_ms, 1),
            "zero_lag_correlation": round(zero_lag_corr, 4),
        }

        return combined, metrics

    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    # Layer 2: Energy Event Correspondence
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    def _analyze_event_correspondence(
        self, audio_env: np.ndarray, lip_signal: np.ndarray,
        fps: float,
    ) -> Tuple[float, Dict]:
        """
        Check if audio energy bursts correspond to lip movement events.

        Method:
        1. Detect peaks in audio envelope (speech energy bursts)
        2. Detect peaks in lip movement (mouth openings)
        3. Check how many audio peaks have a corresponding lip peak nearby
        """
        # Detect peaks: local maxima above median
        def detect_peaks(signal, min_distance=3):
            median = np.median(signal)
            peaks = []
            for i in range(1, len(signal) - 1):
                if signal[i] > signal[i - 1] and signal[i] > signal[i + 1]:
                    if signal[i] > median:
                        if not peaks or (i - peaks[-1]) >= min_distance:
                            peaks.append(i)
            return peaks

        audio_peaks = detect_peaks(audio_env, min_distance=int(fps * 0.1))
        lip_peaks = detect_peaks(lip_signal, min_distance=int(fps * 0.1))

        if len(audio_peaks) < 3 or len(lip_peaks) < 3:
            return 0.5, {"error": "too few events detected",
                         "audio_peaks": len(audio_peaks),
                         "lip_peaks": len(lip_peaks)}

        # Match audio peaks to nearest lip peaks
        match_window = int(fps * 0.15)  # ±150ms window
        matched = 0
        match_delays = []

        for ap in audio_peaks:
            best_dist = float('inf')
            for lp in lip_peaks:
                dist = abs(ap - lp)
                if dist < best_dist:
                    best_dist = dist
            if best_dist <= match_window:
                matched += 1
                match_delays.append(best_dist / fps * 1000)  # ms

        match_ratio = matched / len(audio_peaks)
        avg_delay = float(np.mean(match_delays)) if match_delays else 0
        delay_std = float(np.std(match_delays)) if len(match_delays) >= 2 else 0

        # Event count ratio (should be similar for real speech)
        count_ratio = min(len(audio_peaks), len(lip_peaks)) / (max(len(audio_peaks), len(lip_peaks)) + 1e-6)

        # Score
        # match_ratio: real ~0.6-0.9, AI ~0.2-0.5
        match_score = np.clip((0.55 - match_ratio) / 0.35, 0, 1)

        # count_ratio: real ~0.6-0.9, AI ~0.3-0.6
        count_score = np.clip((0.6 - count_ratio) / 0.30, 0, 1)

        # delay consistency: real ~5-15ms std, AI ~15-50+ms std
        delay_score = np.clip((delay_std - 10) / 30, 0, 1)

        combined = match_score * 0.45 + count_score * 0.30 + delay_score * 0.25

        metrics = {
            "audio_peaks": len(audio_peaks),
            "lip_peaks": len(lip_peaks),
            "match_ratio": round(match_ratio, 4),
            "avg_match_delay_ms": round(avg_delay, 1),
            "match_delay_std_ms": round(delay_std, 1),
            "event_count_ratio": round(count_ratio, 4),
        }

        return float(np.clip(combined, 0, 1)), metrics

    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    # Layer 3: Speech Rhythm Alignment
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    def _analyze_speech_rhythm(
        self, audio_env: np.ndarray, lip_signal: np.ndarray,
        fps: float,
    ) -> Tuple[float, Dict]:
        """
        Compare dominant rhythm frequencies in audio and lip signals.

        Speech has a characteristic syllable rate (~3-7 Hz). This rhythm
        should appear in both the audio envelope and lip movement signal
        at the same frequency.
        """
        # FFT of both signals
        n = len(audio_env)
        freqs = np.fft.rfftfreq(n, d=1.0 / fps)

        audio_fft = np.abs(np.fft.rfft(audio_env - audio_env.mean()))
        lip_fft = np.abs(np.fft.rfft(lip_signal - lip_signal.mean()))

        # Focus on speech rhythm range (2-8 Hz = syllable rate)
        rhythm_mask = (freqs >= 2.0) & (freqs <= 8.0)

        if not np.any(rhythm_mask):
            return 0.5, {"error": "insufficient frequency resolution"}

        audio_rhythm = audio_fft[rhythm_mask]
        lip_rhythm = lip_fft[rhythm_mask]
        rhythm_freqs = freqs[rhythm_mask]

        # Dominant frequency in each
        audio_peak_freq = rhythm_freqs[np.argmax(audio_rhythm)]
        lip_peak_freq = rhythm_freqs[np.argmax(lip_rhythm)]

        freq_diff = abs(audio_peak_freq - lip_peak_freq)

        # Spectral correlation in rhythm band
        if len(audio_rhythm) >= 3:
            spectral_corr = float(np.corrcoef(
                audio_rhythm / (audio_rhythm.max() + 1e-8),
                lip_rhythm / (lip_rhythm.max() + 1e-8),
            )[0, 1])
            if np.isnan(spectral_corr):
                spectral_corr = 0.0
        else:
            spectral_corr = 0.0

        # Score
        # freq_diff: real ~0.0-0.5 Hz, AI ~0.5-3.0+ Hz
        freq_score = np.clip((freq_diff - 0.2) / 1.5, 0, 1)

        # spectral_corr: real ~0.4-0.8, AI ~-0.1-0.3
        corr_score = np.clip((0.35 - spectral_corr) / 0.40, 0, 1)

        combined = freq_score * 0.45 + corr_score * 0.55

        metrics = {
            "audio_peak_rhythm_hz": round(float(audio_peak_freq), 2),
            "lip_peak_rhythm_hz": round(float(lip_peak_freq), 2),
            "rhythm_freq_diff_hz": round(freq_diff, 2),
            "rhythm_spectral_correlation": round(spectral_corr, 4),
        }

        return float(np.clip(combined, 0, 1)), metrics

    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    # Layer 4: Silence-Stillness Correspondence
    # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    def _analyze_silence_stillness(
        self, audio_env: np.ndarray, lip_signal: np.ndarray,
    ) -> Tuple[float, Dict]:
        """
        Check if lip movement stops during audio silence and vice versa.

        Real: silence → lips still, speech → lips move
        AI: lips may move during silence, or stay still during speech
        """
        # Thresholds for silence and stillness
        audio_threshold = np.percentile(audio_env, 25)
        lip_threshold = np.percentile(lip_signal, 25)

        silent_frames = audio_env < audio_threshold
        still_frames = lip_signal < lip_threshold

        n = len(audio_env)

        # Correspondence: silence ↔ stillness
        silence_still = np.sum(silent_frames & still_frames)
        silence_moving = np.sum(silent_frames & ~still_frames)
        speech_still = np.sum(~silent_frames & still_frames)
        speech_moving = np.sum(~silent_frames & ~still_frames)

        # Real: high silence_still + speech_moving, low silence_moving + speech_still
        n_concordant = silence_still + speech_moving
        n_discordant = silence_moving + speech_still
        concordance = n_concordant / (n + 1e-6)

        # Specifically problematic: lips moving during silence
        if silent_frames.sum() > 0:
            moving_in_silence_ratio = silence_moving / (silent_frames.sum() + 1e-6)
        else:
            moving_in_silence_ratio = 0

        # And lips still during speech
        if (~silent_frames).sum() > 0:
            still_in_speech_ratio = speech_still / ((~silent_frames).sum() + 1e-6)
        else:
            still_in_speech_ratio = 0

        # Score
        # concordance: real ~0.6-0.8, AI ~0.4-0.6
        conc_score = np.clip((0.6 - concordance) / 0.20, 0, 1)

        # moving_in_silence_ratio: real ~0.1-0.3, AI ~0.3-0.6+
        silence_score = np.clip((moving_in_silence_ratio - 0.15) / 0.30, 0, 1)

        # still_in_speech_ratio: real ~0.1-0.3, AI ~0.3-0.6+
        speech_score = np.clip((still_in_speech_ratio - 0.15) / 0.30, 0, 1)

        combined = conc_score * 0.30 + silence_score * 0.40 + speech_score * 0.30

        metrics = {
            "concordance_ratio": round(concordance, 4),
            "moving_in_silence_ratio": round(moving_in_silence_ratio, 4),
            "still_in_speech_ratio": round(still_in_speech_ratio, 4),
            "n_silent_frames": int(silent_frames.sum()),
            "n_speech_frames": int((~silent_frames).sum()),
        }

        return float(np.clip(combined, 0, 1)), metrics
