"""
Temporal Frequency Analyzer
============================
Detects AI-generated video by analyzing frequency-domain patterns
across the temporal axis (frame-to-frame).

Key insight: Real video captured by cameras has temporal frequency
characteristics determined by:
- Shutter speed and motion blur
- Sensor readout (rolling shutter)
- Scene motion dynamics
- Camera stabilization

AI-generated video has different temporal frequency signatures:

1. **Temporal Flicker Spectrum**: Real video has smooth temporal power
   decay. AI video often shows periodic flicker at specific frequencies
   related to the generation process (diffusion steps, autoregressive
   frame generation window).

2. **Motion Frequency Distribution**: Real motion follows physical
   laws (inertia, gravity). AI motion may have unnatural frequency
   components (too smooth or with periodic artifacts).

3. **Noise Temporal Correlation**: Camera sensor noise is temporally
   uncorrelated (white noise in time). AI "noise" may be temporally
   correlated (generated by the same model across frames).

4. **Color Drift**: AI video may show subtle color temperature changes
   across frames that don't match physical lighting.
"""

import logging
import numpy as np
import cv2

logger = logging.getLogger(__name__)


class TemporalFrequencyAnalyzer:
    """Analyzes temporal frequency patterns for AI video detection."""

    def analyze(self, frames: list) -> dict:
        """
        Analyze temporal frequency patterns across video frames.

        Args:
            frames: List of BGR frames (numpy arrays).

        Returns:
            dict with score, confidence, sub-scores, and anomalies.
        """
        if len(frames) < 8:
            return self._fallback_result("Not enough frames for temporal analysis")

        # Sample frames evenly
        n_sample = min(64, len(frames))
        indices = np.linspace(0, len(frames) - 1, n_sample, dtype=int)
        sampled = [frames[i] for i in indices]

        # Convert to grayscale array
        grays = np.array([cv2.cvtColor(f, cv2.COLOR_BGR2GRAY).astype(np.float64) for f in sampled])
        # Resize for efficiency
        target_h, target_w = 128, 128
        grays = np.array([cv2.resize(g, (target_w, target_h)) for g in grays])

        anomalies = []

        # 1. Temporal flicker spectrum
        flicker_score = self._analyze_temporal_flicker(grays)

        # 2. Motion frequency distribution
        motion_score = self._analyze_motion_frequency(grays)

        # 3. Noise temporal correlation
        noise_corr_score = self._analyze_noise_correlation(grays)

        # 4. Color drift analysis
        color_drift_score = self._analyze_color_drift(sampled)

        # 5. Frame-to-frame consistency entropy
        consistency_score = self._analyze_consistency_entropy(grays)

        if flicker_score > 0.55:
            anomalies.append(f"Temporal flicker anomaly ({flicker_score:.2f})")
        if motion_score > 0.55:
            anomalies.append(f"Motion frequency anomaly ({motion_score:.2f})")
        if noise_corr_score > 0.55:
            anomalies.append(f"Temporal noise correlation anomaly ({noise_corr_score:.2f})")
        if color_drift_score > 0.55:
            anomalies.append(f"Color drift detected ({color_drift_score:.2f})")
        if consistency_score > 0.55:
            anomalies.append(f"Frame consistency anomaly ({consistency_score:.2f})")

        weights = np.array([0.25, 0.20, 0.20, 0.20, 0.15])
        scores = np.array([flicker_score, motion_score, noise_corr_score, color_drift_score, consistency_score])
        final_score = float(np.dot(scores, weights))

        confidence = (
            0.5 * (1.0 - float(np.std(scores)))
            + 0.3 * float(np.max(scores))
            + 0.2 * min(1.0, len(anomalies) / 3)
        )

        return {
            "score": float(np.clip(final_score, 0.0, 1.0)),
            "confidence": float(np.clip(confidence, 0.0, 1.0)),
            "flicker_score": float(flicker_score),
            "motion_frequency_score": float(motion_score),
            "noise_correlation_score": float(noise_corr_score),
            "color_drift_score": float(color_drift_score),
            "consistency_score": float(consistency_score),
            "n_frames_analyzed": len(sampled),
            "anomalies": anomalies,
        }

    def _analyze_temporal_flicker(self, grays: np.ndarray) -> float:
        """
        Analyze temporal flicker in pixel intensity across frames.

        Compute per-pixel temporal FFT and analyze the frequency spectrum.
        """
        n_frames, h, w = grays.shape

        if n_frames < 8:
            return 0.3

        # Sample spatial locations
        n_pixels = 200
        rng = np.random.RandomState(42)
        ys = rng.randint(0, h, n_pixels)
        xs = rng.randint(0, w, n_pixels)

        # Extract temporal signals at sampled locations
        temporal_signals = grays[:, ys, xs]  # (n_frames, n_pixels)

        # Compute FFT for each pixel's temporal signal
        temporal_fft = np.abs(np.fft.rfft(temporal_signals, axis=0))  # (n_freq, n_pixels)

        # Average power spectrum across pixels
        mean_spectrum = np.mean(temporal_fft ** 2, axis=1)

        if mean_spectrum[0] < 1e-10:
            return 0.3

        # Normalize (exclude DC)
        mean_spectrum_norm = mean_spectrum[1:] / (mean_spectrum[1:].sum() + 1e-10)

        scores = []

        # Check for spectral peaks (AI flicker)
        if len(mean_spectrum_norm) > 5:
            # Smoothed baseline
            from scipy.ndimage import gaussian_filter1d
            smoothed = gaussian_filter1d(mean_spectrum_norm, sigma=2)
            residual = mean_spectrum_norm - smoothed

            # Peak detection
            peak_magnitude = np.max(np.abs(residual))
            if peak_magnitude > 0.1:
                scores.append(0.7)  # Strong temporal flicker peak
            elif peak_magnitude > 0.05:
                scores.append(0.45)
            else:
                scores.append(0.15)

        # Spectral decay rate
        # Real video: smooth decay (motion blur, natural motion)
        # AI: flatter spectrum or unusual decay
        if len(mean_spectrum_norm) > 3:
            log_spec = np.log(mean_spectrum_norm + 1e-10)
            freqs = np.arange(1, len(log_spec) + 1).astype(float)
            coeffs = np.polyfit(np.log(freqs), log_spec, 1)
            decay_rate = -coeffs[0]

            # Real: decay rate 1.0-3.0
            # AI: often < 0.8 (too flat) or > 4.0 (too steep)
            if decay_rate < 0.5 or decay_rate > 5.0:
                scores.append(0.65)
            elif decay_rate < 0.8 or decay_rate > 3.5:
                scores.append(0.4)
            else:
                scores.append(0.15)

        return float(np.mean(scores)) if scores else 0.3

    def _analyze_motion_frequency(self, grays: np.ndarray) -> float:
        """
        Analyze the frequency distribution of inter-frame motion.
        """
        n_frames = len(grays)
        if n_frames < 5:
            return 0.3

        # Compute optical flow magnitude between consecutive frames
        flow_magnitudes = []
        for i in range(1, n_frames):
            flow = cv2.calcOpticalFlowFarneback(
                grays[i - 1].astype(np.uint8),
                grays[i].astype(np.uint8),
                None, 0.5, 3, 15, 3, 5, 1.2, 0
            )
            mag = np.sqrt(flow[:, :, 0] ** 2 + flow[:, :, 1] ** 2)
            flow_magnitudes.append(np.mean(mag))

        flow_magnitudes = np.array(flow_magnitudes)

        if len(flow_magnitudes) < 4:
            return 0.3

        scores = []

        # Motion smoothness (should follow physics)
        motion_diff = np.diff(flow_magnitudes)
        motion_jerk = np.diff(motion_diff)

        # Jerk distribution
        if len(motion_jerk) > 2:
            jerk_cv = np.std(motion_jerk) / (np.mean(np.abs(motion_jerk)) + 1e-10)
            # Real: moderate jerk (CV 0.5-2.0)
            # AI: may have too uniform or too erratic motion changes
            if jerk_cv < 0.3:
                scores.append(0.6)  # Too smooth
            elif jerk_cv > 3.0:
                scores.append(0.55)  # Too erratic
            else:
                scores.append(0.15)

        # Motion temporal FFT
        if len(flow_magnitudes) >= 8:
            motion_fft = np.abs(np.fft.rfft(flow_magnitudes - np.mean(flow_magnitudes)))
            if motion_fft.sum() > 1e-10:
                motion_spec = motion_fft / motion_fft.sum()
                motion_entropy = -np.sum(motion_spec[motion_spec > 0] * np.log2(motion_spec[motion_spec > 0] + 1e-10))
                max_entropy = np.log2(len(motion_spec))

                # Very high entropy = random motion (not physically plausible)
                # Very low entropy = perfectly periodic motion (AI artifact)
                norm_entropy = motion_entropy / max_entropy
                if norm_entropy > 0.92 or norm_entropy < 0.3:
                    scores.append(0.6)
                else:
                    scores.append(0.15)

        return float(np.mean(scores)) if scores else 0.3

    def _analyze_noise_correlation(self, grays: np.ndarray) -> float:
        """
        Analyze temporal correlation of noise across frames.

        Camera noise is temporally uncorrelated (white).
        AI "noise" is often temporally correlated (same generator).
        """
        n_frames = len(grays)
        if n_frames < 5:
            return 0.3

        # Extract noise by subtracting temporal mean
        temporal_mean = np.mean(grays, axis=0)
        noise_frames = grays - temporal_mean

        # Compute temporal autocorrelation of noise at sampled locations
        h, w = noise_frames.shape[1:]
        n_pixels = 100
        rng = np.random.RandomState(42)
        ys = rng.randint(0, h, n_pixels)
        xs = rng.randint(0, w, n_pixels)

        noise_signals = noise_frames[:, ys, xs]  # (n_frames, n_pixels)

        # Lag-1 autocorrelation per pixel
        lag1_corrs = []
        for p in range(n_pixels):
            signal = noise_signals[:, p]
            if np.std(signal) < 0.01:
                continue
            n = len(signal) - 1
            corr = np.corrcoef(signal[:-1], signal[1:])[0, 1]
            if not np.isnan(corr):
                lag1_corrs.append(corr)

        if len(lag1_corrs) < 20:
            return 0.3

        mean_lag1_corr = np.mean(lag1_corrs)

        # Camera noise: lag-1 correlation ≈ 0 (uncorrelated)
        # AI noise: lag-1 correlation > 0.2 (temporally correlated)
        if abs(mean_lag1_corr) > 0.35:
            return 0.8
        elif abs(mean_lag1_corr) > 0.20:
            return 0.6
        elif abs(mean_lag1_corr) > 0.10:
            return 0.35
        else:
            return 0.1

    def _analyze_color_drift(self, frames: list) -> float:
        """
        Detect color temperature drift across frames.

        Real video: consistent white balance (unless lighting changes).
        AI video: may have subtle color shifts between frames.
        """
        if len(frames) < 5:
            return 0.3

        # Extract average color per frame
        avg_colors = []
        for frame in frames:
            avg_bgr = frame.mean(axis=(0, 1))
            avg_colors.append(avg_bgr)

        avg_colors = np.array(avg_colors)

        # Color temperature proxy: R/B ratio
        rb_ratio = avg_colors[:, 2] / (avg_colors[:, 0] + 1e-5)

        # Frame-to-frame color change
        color_diff = np.diff(avg_colors, axis=0)
        color_change = np.linalg.norm(color_diff, axis=1)

        scores = []

        # R/B ratio consistency
        rb_cv = np.std(rb_ratio) / (np.mean(rb_ratio) + 1e-10)
        if rb_cv > 0.08:
            scores.append(0.65)  # Significant color drift
        elif rb_cv > 0.04:
            scores.append(0.4)
        else:
            scores.append(0.15)

        # Smoothness of color change (should be smooth for real video)
        if len(color_change) > 3:
            cc_jerk = np.diff(color_change)
            cc_jerk_cv = np.std(cc_jerk) / (np.mean(np.abs(cc_jerk)) + 1e-10)
            if cc_jerk_cv > 2.0:
                scores.append(0.55)  # Erratic color changes
            else:
                scores.append(0.15)

        return float(np.mean(scores))

    def _analyze_consistency_entropy(self, grays: np.ndarray) -> float:
        """
        Analyze entropy of frame-to-frame differences.

        Real: difference images have structured content (edges, motion).
        AI: may have different entropy characteristics.
        """
        n_frames = len(grays)
        if n_frames < 5:
            return 0.3

        diff_entropies = []
        for i in range(1, min(n_frames, 30)):
            diff = np.abs(grays[i] - grays[i - 1])
            # Quantize for histogram
            diff_q = (diff / 4).astype(int).clip(0, 63)
            hist = np.histogram(diff_q, bins=64, range=(0, 63))[0].astype(float)
            hist = hist / (hist.sum() + 1e-10)
            entropy = -np.sum(hist[hist > 0] * np.log2(hist[hist > 0] + 1e-10))
            diff_entropies.append(entropy)

        if len(diff_entropies) < 3:
            return 0.3

        mean_entropy = np.mean(diff_entropies)
        std_entropy = np.std(diff_entropies)
        cv_entropy = std_entropy / (mean_entropy + 1e-10)

        # Real: moderate entropy with natural variation (CV 0.1-0.4)
        # AI: too uniform entropy (CV < 0.05) or unusual mean
        if cv_entropy < 0.03:
            return 0.65  # Suspiciously uniform frame differences
        elif cv_entropy < 0.08:
            return 0.4
        else:
            return 0.15

    def _fallback_result(self, reason: str = "") -> dict:
        return {
            "score": 0.5,
            "confidence": 0.0,
            "flicker_score": 0.5,
            "motion_frequency_score": 0.5,
            "noise_correlation_score": 0.5,
            "color_drift_score": 0.5,
            "consistency_score": 0.5,
            "n_frames_analyzed": 0,
            "anomalies": [reason] if reason else [],
        }
